# Generated by Django 5.0.4 on 2024-04-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.TextField(max_length=255)),
                ("email", models.TextField(max_length=255)),
                ("passaword", models.TextField(max_length=255)),
            ],
        ),
    ]
